

import { GET_HOME_DATA, GET_MASCOTAS, GET_RAZAS } from './Query'
import { CREATE_RAZA, UPDATE_RAZA, DELETE_RAZA, CREATE_MASCOTA, UPDATE_MASCOTA, DELETE_MASCOTA } from './Mutation'


export {

    GET_HOME_DATA, GET_MASCOTAS, GET_RAZAS,

    CREATE_RAZA, UPDATE_RAZA, DELETE_RAZA, CREATE_MASCOTA, UPDATE_MASCOTA, DELETE_MASCOTA

 }

